# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nb2md": "convert.ipynb",
         "parallel_nb2md": "convert.ipynb",
         "nbdoc_build": "convert.ipynb",
         "InjectMeta": "mdx.ipynb",
         "StripAnsi": "mdx.ipynb",
         "InsertWarning": "mdx.ipynb",
         "RmEmptyCode": "mdx.ipynb",
         "MetaflowTruncate": "mdx.ipynb",
         "UpdateTags": "mdx.ipynb",
         "MetaflowSelectSteps": "mdx.ipynb",
         "WriteTitle": "mdx.ipynb",
         "CleanMagics": "mdx.ipynb",
         "BashIdentify": "mdx.ipynb",
         "get_mdx_exporter": "mdx.ipynb",
         "is_valid_xml": "showdoc.ipynb",
         "param2JSX": "showdoc.ipynb",
         "np2jsx": "showdoc.ipynb",
         "fmt_sig_param": "showdoc.ipynb",
         "get_sig_section": "showdoc.ipynb",
         "get_jsx_doc": "showdoc.ipynb"}

modules = ["convert.py",
           "mdx.py",
           "showdoc.py"]

doc_url = "https://outerbounds.github.io/nbdoc/"

git_url = "https://github.com/outerbounds/nbdoc/tree/master/"

def custom_doc_links(name): return None
