# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CleanOutput": "mdx.ipynb",
         "WriteTitle": "mdx.ipynb",
         "CleanMagics": "mdx.ipynb",
         "BashIdentify": "mdx.ipynb",
         "get_mdx_exporter": "mdx.ipynb"}

modules = ["mdx.py"]

doc_url = "https://outerbounds.github.io/nbdoc/"

git_url = "https://github.com/outerbounds/nbdoc/tree/master/"

def custom_doc_links(name): return None
