# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nb2md": "convert.ipynb",
         "parallel_nb2md": "convert.ipynb",
         "nbdoc_build": "convert.ipynb",
         "InjectMeta": "mdx.ipynb",
         "StripAnsi": "mdx.ipynb",
         "InsertWarning": "mdx.ipynb",
         "RmEmptyCode": "mdx.ipynb",
         "MetaflowTruncate": "mdx.ipynb",
         "UpdateTags": "mdx.ipynb",
         "MetaflowSelectSteps": "mdx.ipynb",
         "WriteTitle": "mdx.ipynb",
         "CleanFlags": "mdx.ipynb",
         "CleanMagics": "mdx.ipynb",
         "Black": "mdx.ipynb",
         "black_mode": "mdx.ipynb",
         "CatFiles": "mdx.ipynb",
         "BashIdentify": "mdx.ipynb",
         "CleanShowDoc": "mdx.ipynb",
         "get_mdx_exporter": "mdx.ipynb",
         "HTMLdf": "media.ipynb",
         "HTMLEscape": "media.ipynb",
         "ImageSave": "media.ipynb",
         "ImagePath": "media.ipynb",
         "nbrun": "run.ipynb",
         "nbupdate": "run.ipynb",
         "parallel_nbupdate": "run.ipynb",
         "nbdoc_update": "run.ipynb",
         "is_valid_xml": "showdoc.ipynb",
         "param2JSX": "showdoc.ipynb",
         "np2jsx": "showdoc.ipynb",
         "fmt_sig_param": "showdoc.ipynb",
         "get_sig_section": "showdoc.ipynb",
         "get_type": "showdoc.ipynb",
         "get_base_urls": "showdoc.ipynb",
         "ShowDoc": "showdoc.ipynb",
         "run_preprocessor": "test_utils.ipynb",
         "show_plain_md": "test_utils.ipynb"}

modules = ["convert.py",
           "mdx.py",
           "media.py",
           "run.py",
           "showdoc.py",
           "test_utils.py"]

doc_url = "https://outerbounds.github.io/nbdoc/"

git_url = "https://github.com/outerbounds/nbdoc/tree/master/"

def custom_doc_links(name): return None
