# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/convert.ipynb (unless otherwise specified).

__all__ = ['nb2md']

# Cell
from .mdx import get_mdx_exporter
from typing import Union
from nbdev.export import nbglob
from nbconvert.exporters import Exporter
from fastcore.all import Path

# Cell
def nb2md(fname:Union[str, Path], exp:Exporter):
    "Convert a notebook in `fname` to a markdown file."
    file = Path(fname)
    assert file.name.endswith('.ipynb'), f'{str(fname)} is not a notebook.'
    assert file.is_file(), f'file {str(fname)} not found.'
    o,r = exp.from_filename(fname)
    file.with_suffix('.md').write_text(o)